# -*- coding: utf-8 -*-
"""bluring of animation(cla 3) CV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKoaN24IzzDUPhEBWGh8g6J4LZEELOxU
"""

import cv2
import matplotlib.pyplot as plt

# Function to display original and blurred images
def show_comparison(original, blur3, blur5, blur7, title):
    plt.figure(figsize=(12, 10))

    # Original Image
    plt.subplot(2, 2, 1)
    plt.imshow(original, cmap='gray')
    plt.title(f'{title} - Original')
    plt.axis('off')

    # 3x3 Average Filter
    plt.subplot(2, 2, 2)
    plt.imshow(blur3, cmap='gray')
    plt.title('Average Filter (3×3)')
    plt.axis('off')

    # 5x5 Average Filter
    plt.subplot(2, 2, 3)
    plt.imshow(blur5, cmap='gray')
    plt.title('Average Filter (5×5)')
    plt.axis('off')

    # 7x7 Average Filter
    plt.subplot(2, 2, 4)
    plt.imshow(blur7, cmap='gray')
    plt.title('Average Filter (7×7)')
    plt.axis('off')

    plt.tight_layout()
    plt.show()


# Image paths
image_paths = [
    "/content/drive/MyDrive/CV image/ronaldo.jpg",
    "/content/drive/MyDrive/CV image/bighorn goat.jpg"
]

# Process each image
for i, path in enumerate(image_paths, start=1):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

    if img is None:
        print(f"Error loading image: {path}")
        continue

    # Display loaded image
    plt.figure(figsize=(5, 5))
    plt.imshow(img, cmap='gray')
    plt.title(f'Loaded Image {i}')
    plt.axis('off')
    plt.show()

    # Apply average filters
    blur3 = cv2.blur(img, (3, 3))
    blur5 = cv2.blur(img, (5, 5))
    blur7 = cv2.blur(img, (7, 7))

    # Display comparison
    show_comparison(img, blur3, blur5, blur7, f'Image {i}')

